#+title: Week1


* Problem 3:

Staff are finding it increasing more difficult keeping track of students who miss
assessments because of individual extenuating circumstances and students with
disabilities requiring special exam assistance.

** Problem statement Draft:

- Staff need a more cohesive system to monitor specific student requirements and exceptions
  that affects the natural flow of delivering exams. Currently students need to manually fill out an
  IEEC form and have that approved externally and inform their lecturer, and some lecturers may not
  agree on the severity of the reason for the IEEC. On top of this in terms of manual intervention,
  after student is accepted for disabilty accomadation, they have to explcitly inform each lecturer
  of their individual exam accomadations and they need to be reminded every exam, which at times
  may lead to lectureres forgetting to accomadate these particular needs.


** User roles:
- Lecturers
- Students with Individual extenuating circumstances
- Students entitled to Disability Support Services
*** Lecturers
  1. If this system were to be developed, how closely would you like it involved with students? (None at all or universally).
  2. Would you like there to be an entirely different interface for DSS
     and IEEC or would you prefer them to be all together?
  3. Would you like to see the details of certain IEECs or do you
     think it should be anonymous?
  4. Would persistent notifications about these IEEcs and DSS accomadations frustrate you or find it more helpful to ensure exam conditions are fully met (Opt in by default or opt out)?
*** DSS Students

1. What aspect of seeking the DSS exam assistance do you find the hardest?
2. Do many lecturers not comply with your given needs?
3. Would you like to be able to direcetly connect with the lecturers here or just have it simply as a bridge to have your DSS needs met?
4. How do you currently ensure your needs are met (email,in person, through canvas)?
*** Students who have gone through IEECs
1. Would you like this system to replace the entire form filling system (Have everything to do with IEECs be centralised)?
2. How often do you find yourself reaching for an IEEC since you have originally?
3. Do some lecturers/administrators deny your IEECs?
4. Would you like the IEECs to be reviewed by your lecturers or exclusively externally?

** Team roles

1. Team lead - The member of the team which determines the content of the sprints and what we must deliver
2. Administrator - Once the product has been launched, the member who will adjust any data internally within the projects frontend/backend
3. Maintainer - Once the product has been launched, the team member who will tackle any bugs or issues with the new system.
4. Tester - Member of the team deployed to act like a staff member and will strain the application to its limits to find any issues compared to the given requirements

** 5 questions for Stakeholders:

- Does this need to be accessed universally (As a website or a desktop and mobile app)?
- Would you like to collect any data in particular for future DSS and IEEC requests?
- Will external documentation be required or tutorials within the application itself?
- Will there be visually/audibly impaired users utilizing this application?
- How involved would you like students to be in this application (Just to give their IEEC/DSS Requests)?
* Vision Statement


This product is primarily For staff members managing exams who find it hard to keep track of these students needs. The ENMS (Exam needs managements System)
is a web app That allows both staff and students to prevent any conflicts for exam accomadations as a result of disability needs or unforseen circumstances
Unlike the current system which is primarily done in confidence between student and lecturer and has little to no guarantee of concrete results
Our product will ensure no student will be left in the unknown on their exam performance due to variable aspects of their lives outside of their control
