// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gameman.proto

package distribSys

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameManService_CreateGame_FullMethodName  = "/distrib_sys.v1.GameManService/CreateGame"
	GameManService_SubmitGuess_FullMethodName = "/distrib_sys.v1.GameManService/SubmitGuess"
	GameManService_GetSummary_FullMethodName  = "/distrib_sys.v1.GameManService/GetSummary"
)

// GameManServiceClient is the client API for GameManService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameManServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	SubmitGuess(ctx context.Context, in *SubmitGuessRequest, opts ...grpc.CallOption) (*SubmitGuessResponse, error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
}

type gameManServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameManServiceClient(cc grpc.ClientConnInterface) GameManServiceClient {
	return &gameManServiceClient{cc}
}

func (c *gameManServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, GameManService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManServiceClient) SubmitGuess(ctx context.Context, in *SubmitGuessRequest, opts ...grpc.CallOption) (*SubmitGuessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitGuessResponse)
	err := c.cc.Invoke(ctx, GameManService_SubmitGuess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, GameManService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameManServiceServer is the server API for GameManService service.
// All implementations must embed UnimplementedGameManServiceServer
// for forward compatibility.
type GameManServiceServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	SubmitGuess(context.Context, *SubmitGuessRequest) (*SubmitGuessResponse, error)
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	mustEmbedUnimplementedGameManServiceServer()
}

// UnimplementedGameManServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameManServiceServer struct{}

func (UnimplementedGameManServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameManServiceServer) SubmitGuess(context.Context, *SubmitGuessRequest) (*SubmitGuessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitGuess not implemented")
}
func (UnimplementedGameManServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedGameManServiceServer) mustEmbedUnimplementedGameManServiceServer() {}
func (UnimplementedGameManServiceServer) testEmbeddedByValue()                        {}

// UnsafeGameManServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameManServiceServer will
// result in compilation errors.
type UnsafeGameManServiceServer interface {
	mustEmbedUnimplementedGameManServiceServer()
}

func RegisterGameManServiceServer(s grpc.ServiceRegistrar, srv GameManServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameManServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameManService_ServiceDesc, srv)
}

func _GameManService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManService_SubmitGuess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitGuessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManServiceServer).SubmitGuess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManService_SubmitGuess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManServiceServer).SubmitGuess(ctx, req.(*SubmitGuessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameManService_ServiceDesc is the grpc.ServiceDesc for GameManService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameManService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrib_sys.v1.GameManService",
	HandlerType: (*GameManServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameManService_CreateGame_Handler,
		},
		{
			MethodName: "SubmitGuess",
			Handler:    _GameManService_SubmitGuess_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _GameManService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameman.proto",
}

const (
	PangramService_GetPangram_FullMethodName   = "/distrib_sys.v1.PangramService/GetPangram"
	PangramService_GetGameState_FullMethodName = "/distrib_sys.v1.PangramService/GetGameState"
)

// PangramServiceClient is the client API for PangramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PangramServiceClient interface {
	GetPangram(ctx context.Context, in *GetPangramRequest, opts ...grpc.CallOption) (*GetPangramResponse, error)
	GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error)
}

type pangramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPangramServiceClient(cc grpc.ClientConnInterface) PangramServiceClient {
	return &pangramServiceClient{cc}
}

func (c *pangramServiceClient) GetPangram(ctx context.Context, in *GetPangramRequest, opts ...grpc.CallOption) (*GetPangramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPangramResponse)
	err := c.cc.Invoke(ctx, PangramService_GetPangram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pangramServiceClient) GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStateResponse)
	err := c.cc.Invoke(ctx, PangramService_GetGameState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PangramServiceServer is the server API for PangramService service.
// All implementations must embed UnimplementedPangramServiceServer
// for forward compatibility.
type PangramServiceServer interface {
	GetPangram(context.Context, *GetPangramRequest) (*GetPangramResponse, error)
	GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error)
	mustEmbedUnimplementedPangramServiceServer()
}

// UnimplementedPangramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPangramServiceServer struct{}

func (UnimplementedPangramServiceServer) GetPangram(context.Context, *GetPangramRequest) (*GetPangramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPangram not implemented")
}
func (UnimplementedPangramServiceServer) GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameState not implemented")
}
func (UnimplementedPangramServiceServer) mustEmbedUnimplementedPangramServiceServer() {}
func (UnimplementedPangramServiceServer) testEmbeddedByValue()                        {}

// UnsafePangramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PangramServiceServer will
// result in compilation errors.
type UnsafePangramServiceServer interface {
	mustEmbedUnimplementedPangramServiceServer()
}

func RegisterPangramServiceServer(s grpc.ServiceRegistrar, srv PangramServiceServer) {
	// If the following call pancis, it indicates UnimplementedPangramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PangramService_ServiceDesc, srv)
}

func _PangramService_GetPangram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPangramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PangramServiceServer).GetPangram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PangramService_GetPangram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PangramServiceServer).GetPangram(ctx, req.(*GetPangramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PangramService_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PangramServiceServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PangramService_GetGameState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PangramServiceServer).GetGameState(ctx, req.(*GetGameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PangramService_ServiceDesc is the grpc.ServiceDesc for PangramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PangramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrib_sys.v1.PangramService",
	HandlerType: (*PangramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPangram",
			Handler:    _PangramService_GetPangram_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _PangramService_GetGameState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameman.proto",
}
