// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: gameman.proto

package distribSys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_gameman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type PlayGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameRequest) Reset() {
	*x = PlayGameRequest{}
	mi := &file_gameman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameRequest) ProtoMessage() {}

func (x *PlayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameRequest.ProtoReflect.Descriptor instead.
func (*PlayGameRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{1}
}

func (x *PlayGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubmitGuessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Guess         string                 `protobuf:"bytes,2,opt,name=guess,proto3" json:"guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGuessRequest) Reset() {
	*x = SubmitGuessRequest{}
	mi := &file_gameman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGuessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGuessRequest) ProtoMessage() {}

func (x *SubmitGuessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGuessRequest.ProtoReflect.Descriptor instead.
func (*SubmitGuessRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitGuessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitGuessRequest) GetGuess() string {
	if x != nil {
		return x.Guess
	}
	return ""
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_gameman_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{3}
}

func (x *GetSummaryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPangramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPangramRequest) Reset() {
	*x = GetPangramRequest{}
	mi := &file_gameman_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPangramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPangramRequest) ProtoMessage() {}

func (x *GetPangramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPangramRequest.ProtoReflect.Descriptor instead.
func (*GetPangramRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{4}
}

func (x *GetPangramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_gameman_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_gameman_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGameResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PlayGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Guesses       []string               `protobuf:"bytes,2,rep,name=guesses,proto3" json:"guesses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayGameResponse) Reset() {
	*x = PlayGameResponse{}
	mi := &file_gameman_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayGameResponse) ProtoMessage() {}

func (x *PlayGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayGameResponse.ProtoReflect.Descriptor instead.
func (*PlayGameResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{7}
}

func (x *PlayGameResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayGameResponse) GetGuesses() []string {
	if x != nil {
		return x.Guesses
	}
	return nil
}

type SubmitGuessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewScore      int32                  `protobuf:"varint,1,opt,name=new_score,json=newScore,proto3" json:"new_score,omitempty"`
	WordsGuessed  []string               `protobuf:"bytes,2,rep,name=words_guessed,json=wordsGuessed,proto3" json:"words_guessed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	GameOver      bool                   `protobuf:"varint,4,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGuessResponse) Reset() {
	*x = SubmitGuessResponse{}
	mi := &file_gameman_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGuessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGuessResponse) ProtoMessage() {}

func (x *SubmitGuessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGuessResponse.ProtoReflect.Descriptor instead.
func (*SubmitGuessResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitGuessResponse) GetNewScore() int32 {
	if x != nil {
		return x.NewScore
	}
	return 0
}

func (x *SubmitGuessResponse) GetWordsGuessed() []string {
	if x != nil {
		return x.WordsGuessed
	}
	return nil
}

func (x *SubmitGuessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitGuessResponse) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameType      string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_gameman_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{9}
}

func (x *GetSummaryResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetSummaryResponse) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

type GetPangramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pangram       string                 `protobuf:"bytes,1,opt,name=pangram,proto3" json:"pangram,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPangramResponse) Reset() {
	*x = GetPangramResponse{}
	mi := &file_gameman_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPangramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPangramResponse) ProtoMessage() {}

func (x *GetPangramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPangramResponse.ProtoReflect.Descriptor instead.
func (*GetPangramResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{10}
}

func (x *GetPangramResponse) GetPangram() string {
	if x != nil {
		return x.Pangram
	}
	return ""
}

func (x *GetPangramResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGameStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DisplayLetters string                 `protobuf:"bytes,1,opt,name=display_letters,json=displayLetters,proto3" json:"display_letters,omitempty"`
	CurrentScore   int32                  `protobuf:"varint,2,opt,name=current_score,json=currentScore,proto3" json:"current_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_gameman_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{11}
}

func (x *GetGameStateResponse) GetDisplayLetters() string {
	if x != nil {
		return x.DisplayLetters
	}
	return ""
}

func (x *GetGameStateResponse) GetCurrentScore() int32 {
	if x != nil {
		return x.CurrentScore
	}
	return 0
}

type GameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Guesses       []string               `protobuf:"bytes,2,rep,name=guesses,proto3" json:"guesses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResult) Reset() {
	*x = GameResult{}
	mi := &file_gameman_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResult) ProtoMessage() {}

func (x *GameResult) ProtoReflect() protoreflect.Message {
	mi := &file_gameman_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResult.ProtoReflect.Descriptor instead.
func (*GameResult) Descriptor() ([]byte, []int) {
	return file_gameman_proto_rawDescGZIP(), []int{12}
}

func (x *GameResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameResult) GetGuesses() []string {
	if x != nil {
		return x.Guesses
	}
	return nil
}

var File_gameman_proto protoreflect.FileDescriptor

const file_gameman_proto_rawDesc = "" +
	"\n" +
	"\rgameman.proto\x12\x0edistrib_sys.v1\"'\n" +
	"\x11CreateGameRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"!\n" +
	"\x0fPlayGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x12SubmitGuessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05guess\x18\x02 \x01(\tR\x05guess\"#\n" +
	"\x11GetSummaryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetPangramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13GetGameStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x12CreateGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"B\n" +
	"\x10PlayGameResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x18\n" +
	"\aguesses\x18\x02 \x03(\tR\aguesses\"\x8e\x01\n" +
	"\x13SubmitGuessResponse\x12\x1b\n" +
	"\tnew_score\x18\x01 \x01(\x05R\bnewScore\x12#\n" +
	"\rwords_guessed\x18\x02 \x03(\tR\fwordsGuessed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\tgame_over\x18\x04 \x01(\bR\bgameOver\"J\n" +
	"\x12GetSummaryResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\">\n" +
	"\x12GetPangramResponse\x12\x18\n" +
	"\apangram\x18\x01 \x01(\tR\apangram\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"d\n" +
	"\x14GetGameStateResponse\x12'\n" +
	"\x0fdisplay_letters\x18\x01 \x01(\tR\x0edisplayLetters\x12#\n" +
	"\rcurrent_score\x18\x02 \x01(\x05R\fcurrentScore\"<\n" +
	"\n" +
	"GameResult\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x18\n" +
	"\aguesses\x18\x02 \x03(\tR\aguesses2\x92\x02\n" +
	"\x0eGameManService\x12S\n" +
	"\n" +
	"CreateGame\x12!.distrib_sys.v1.CreateGameRequest\x1a\".distrib_sys.v1.CreateGameResponse\x12V\n" +
	"\vSubmitGuess\x12\".distrib_sys.v1.SubmitGuessRequest\x1a#.distrib_sys.v1.SubmitGuessResponse\x12S\n" +
	"\n" +
	"GetSummary\x12!.distrib_sys.v1.GetSummaryRequest\x1a\".distrib_sys.v1.GetSummaryResponse2\xc0\x01\n" +
	"\x0ePangramService\x12S\n" +
	"\n" +
	"GetPangram\x12!.distrib_sys.v1.GetPangramRequest\x1a\".distrib_sys.v1.GetPangramResponse\x12Y\n" +
	"\fGetGameState\x12#.distrib_sys.v1.GetGameStateRequest\x1a$.distrib_sys.v1.GetGameStateResponseB)Z'distribSys/api/distribSys/v1;distribSysb\x06proto3"

var (
	file_gameman_proto_rawDescOnce sync.Once
	file_gameman_proto_rawDescData []byte
)

func file_gameman_proto_rawDescGZIP() []byte {
	file_gameman_proto_rawDescOnce.Do(func() {
		file_gameman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gameman_proto_rawDesc), len(file_gameman_proto_rawDesc)))
	})
	return file_gameman_proto_rawDescData
}

var file_gameman_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gameman_proto_goTypes = []any{
	(*CreateGameRequest)(nil),    // 0: distrib_sys.v1.CreateGameRequest
	(*PlayGameRequest)(nil),      // 1: distrib_sys.v1.PlayGameRequest
	(*SubmitGuessRequest)(nil),   // 2: distrib_sys.v1.SubmitGuessRequest
	(*GetSummaryRequest)(nil),    // 3: distrib_sys.v1.GetSummaryRequest
	(*GetPangramRequest)(nil),    // 4: distrib_sys.v1.GetPangramRequest
	(*GetGameStateRequest)(nil),  // 5: distrib_sys.v1.GetGameStateRequest
	(*CreateGameResponse)(nil),   // 6: distrib_sys.v1.CreateGameResponse
	(*PlayGameResponse)(nil),     // 7: distrib_sys.v1.PlayGameResponse
	(*SubmitGuessResponse)(nil),  // 8: distrib_sys.v1.SubmitGuessResponse
	(*GetSummaryResponse)(nil),   // 9: distrib_sys.v1.GetSummaryResponse
	(*GetPangramResponse)(nil),   // 10: distrib_sys.v1.GetPangramResponse
	(*GetGameStateResponse)(nil), // 11: distrib_sys.v1.GetGameStateResponse
	(*GameResult)(nil),           // 12: distrib_sys.v1.GameResult
}
var file_gameman_proto_depIdxs = []int32{
	0,  // 0: distrib_sys.v1.GameManService.CreateGame:input_type -> distrib_sys.v1.CreateGameRequest
	2,  // 1: distrib_sys.v1.GameManService.SubmitGuess:input_type -> distrib_sys.v1.SubmitGuessRequest
	3,  // 2: distrib_sys.v1.GameManService.GetSummary:input_type -> distrib_sys.v1.GetSummaryRequest
	4,  // 3: distrib_sys.v1.PangramService.GetPangram:input_type -> distrib_sys.v1.GetPangramRequest
	5,  // 4: distrib_sys.v1.PangramService.GetGameState:input_type -> distrib_sys.v1.GetGameStateRequest
	6,  // 5: distrib_sys.v1.GameManService.CreateGame:output_type -> distrib_sys.v1.CreateGameResponse
	8,  // 6: distrib_sys.v1.GameManService.SubmitGuess:output_type -> distrib_sys.v1.SubmitGuessResponse
	9,  // 7: distrib_sys.v1.GameManService.GetSummary:output_type -> distrib_sys.v1.GetSummaryResponse
	10, // 8: distrib_sys.v1.PangramService.GetPangram:output_type -> distrib_sys.v1.GetPangramResponse
	11, // 9: distrib_sys.v1.PangramService.GetGameState:output_type -> distrib_sys.v1.GetGameStateResponse
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gameman_proto_init() }
func file_gameman_proto_init() {
	if File_gameman_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameman_proto_rawDesc), len(file_gameman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gameman_proto_goTypes,
		DependencyIndexes: file_gameman_proto_depIdxs,
		MessageInfos:      file_gameman_proto_msgTypes,
	}.Build()
	File_gameman_proto = out.File
	file_gameman_proto_goTypes = nil
	file_gameman_proto_depIdxs = nil
}
