#+title: Data Struct

* Elementary Data Structures

** Arrays
- Arrays are the most fundamental linear data structure sometimes called a list or vector.
 #+begin_src java

int[] array = {2,3,4,5,6}

 #+end_src
- They store objects of identical size consecutively in memory
- On a Random Access Machine they can be accessed via the array index in constant time

*** Pointer

- The array index can be a variable in itself, enabling pointer operations such as

 #+begin_src python :file sample.py
    a = [7,9,2,2,3] # Python only used as it is the simplest code to express this problem
    i = 2
    x=a[i]
    print(x)
 #+end_src

 #+RESULTS:
 : None

- Since array indexes are also integers, the random access machines can also perform pointer arithmetic

 #+begin_example
        A[2*i-1]
 #+end_example

- The two conventions on how to address the first element of an array is generally 0 based.
- However we can also have one-based arrays where counting befins at 1??.

  - Which convention is used depends on the context
    - For example java sues zero based arrays
    - The CLRS Book uses one based arrays.


- The arrays length must be allocated. They are static dat structures

  - The ram model assumes ints are stored in each cell hwoever these numbers can be interpreted as other
    primitive data types such as booleans,characters,floats, date and time, memory points using a suitable
    encoding ASCII or IEEE754.
*** Records
- A fixed number of multiple cells can be agregated into a single record sometimes calle d a struct or a tuple.
- Using pointer arithmetic, records can be conceptually treated as single array elemenets.
- Records are often treated as elementary datattypes as well and instead the notation of x = A[i] is used.
- Because the no of elements in a record is constant, the RAM model requires constant access time in this case as well

* Satelite Data
- Conceptually data records are often split into:
  - The Key
  - A pointer to satellite data

- The satellite data can then be ignored by assuming that the pointers are always copied together with the key
- This then simplifies notiation and allows us to focus on what is important

** Multidimensional Arrays
- Arrays can be generalised to more than one dimension, soemtimes called a matrix or table.
  - It is often denoted as: A[i,j] A[i][j]
- Multi dimensional arrays are equivalent to linear arrays using pointer arithmetic.

** What is the index of an element for a given key

- Retrieving and array element for a given index is easy buecuase it is direcetly supported by the RAM mdoel.
- But what about the opposite?
- In this csae every key must be inspected to find the index corresponding to a value V as follows
