#+TITLE: README Distributed Systems assignment 1
#+AUTHOR: Daniel Soden
#+DESCRIPTON: README file explanaing decisions made and planning presented throughout completion of this assignment

#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#project-structure][Project Structure]]
  - [[#file-tree][File tree]]
- [[#design-patterns-used][Design Patterns used]]
  - [[#builder-pattern][Builder Pattern]]
  - [[#singleton-pattern][Singleton Pattern]]
  - [[#adapter-pattern][Adapter Pattern]]
- [[#grpc-usage][gRPC usage]]

* Project Structure
** File tree
- Will be updated and reorganised as time goes on

#+begin_src bash
├── README.org
├── entry.go
├── entryBuilder.go
├── genWord/
│   ├── genWord.go
│   ├── pangrams.json
│   ├── pangrams.py
│   └── words_dictionary.json
├── go.mod
├── main.go
├── pangram.go
└── pangramBuilder.go

2 directories, 14 files

#+end_src

* Design Patterns used
** Builder Pattern

- During this project I made use of the builder pattern as a means of creating entry and pagram structs. Both of those objects have specific parameters that have to have a particular condition to be met to ensure it fits the specs requirements.
  
- For example in the entry program, I implemented the builder pattern to ensure users' entries always are a minimum of 4 characters, otherwise the builder will return nil
  
#+begin_src go
func (eb *entryBuilder) SetLength(letters string) EntryBuilder{
	lenLetters := len(letters)
	if lenLetters < 4{
	  fmt.Println("Word too short try again next time")
	  return nil
	}else{
	eb.entry.length = lenLetters  
	return eb
	}
}
#+end_src

** Singleton Pattern


** Adapter Pattern 


* gRPC usage

- An essential portion of this project is the generation and receipt of pangrams. We were kindly provided with a simple python script that takes words of a particular length from a csv and finds particular pangrams and returns that string to the user. This functionality is completely independent from the games functionality and can be therefore ported over to another machine and the client will receive these strings. 
