-- Creating our postgres db
CREATE DATABASE IF NOT EXISTS compShop;

-- CREATING OUR FIRST TABLE - Customers
 
CREATE TABLE IF NOT EXISTS Customer(
);

CREATE TABLE IF NOT EXISTS Product(
);

CREATE TABLE IF NOT EXISTS Purchases(
);

